name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: nijuda
          path: build/app/outputs/flutter-apk/app-release.apk

      #- name: Run tests
        #run: flutter test

      - name: Analyze project source
        run: flutter analyze
